apiVersion: v1
kind: Service
metadata:
  annotations:
   serviceloadbalancer/lb.host: "grafana.wso2localapps.com"
   serviceloadbalancer/lb.sslTerm: "true"
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-grafana
    exposure-level: public
  name: monitoring-grafana
  namespace: kube-heapster
spec:
  # In a production setup, we recommend accessing Grafana through an external Loadbalancer
  # or through a public IP.
  # type: LoadBalancer
  ports:
  - port: 443
    targetPort: 3000
  selector:
    name: grafana
