apiVersion: v1
kind: Service
metadata:
  annotations:
    serviceloadbalancer/lb.host: "influxdb.wso2localapps.com"
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
    exposure-level: public
  name: monitoring-influxdb
  namespace: kube-heapster
spec:
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  - name: api
    port: 80
    targetPort: 8086
  selector:
    name: influxdb
